/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author fahaw
 */
public class BundleView extends javax.swing.JPanel {

    /**
     * Creates new form BundleView
     */
    private Main main;
    
    public BundleView(Main main) {
        initComponents();
        setOpaque(false);
        this.main = main;

        
    }
    @Override
    protected void paintComponent(Graphics grphcs){
        Graphics2D g2=(Graphics2D)grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#140919"), 0, getHeight(), Color.decode("#190924"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnBundle2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jBtnBundle4 = new javax.swing.JButton();
        jBtnBundle1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jBtnBundle3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(5, 3, 5));
        setMinimumSize(new java.awt.Dimension(830, 770));
        setPreferredSize(new java.awt.Dimension(830, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(231, 219, 239));
        jLabel22.setText("- Free Room 2 Hour(VIP)");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 170, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(231, 219, 239));
        jLabel12.setText("- 1 Calamary");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 170, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 219, 239));
        jLabel6.setText("- 1 Fish n Chip");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 170, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 219, 239));
        jLabel5.setText("FAMILY 4");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 150, 50));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(231, 219, 239));
        jLabel20.setText("- Free Room 2 Hour(Large)");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 170, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(231, 219, 239));
        jLabel10.setText("- Free Room 2 Hour(Small)");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 170, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 219, 239));
        jLabel1.setText("FAMILY 1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, 50));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(231, 219, 239));
        jLabel18.setText("- 2 Mix Platter");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 170, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(231, 219, 239));
        jLabel15.setText("- 1 Pitcher Ice Tea");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 170, 20));

        jLabel9.setBackground(new java.awt.Color(153, 0, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/small.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 150, 150));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(231, 219, 239));
        jLabel19.setText("- 2 Pitcher Ice Tea");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 170, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 219, 239));
        jLabel3.setText("FAMILY 3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 150, 50));

        jBtnBundle2.setBackground(new java.awt.Color(165, 106, 219));
        jBtnBundle2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnBundle2.setForeground(new java.awt.Color(227, 227, 227));
        jBtnBundle2.setText("Book Now");
        jBtnBundle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBundle2ActionPerformed(evt);
            }
        });
        add(jBtnBundle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 219, 239));
        jLabel4.setText("FAMILY 2");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 150, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(231, 219, 239));
        jLabel11.setText("- 1 Pitcher Ice Tea");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 170, 20));

        jLabel7.setBackground(new java.awt.Color(153, 0, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Medium.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 150, 150));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(231, 219, 239));
        jLabel14.setText("- 1 Fish n Chip");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(231, 219, 239));
        jLabel23.setText("- 2 Pitcher Orange Juice");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 170, 20));

        jBtnBundle4.setBackground(new java.awt.Color(165, 106, 219));
        jBtnBundle4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnBundle4.setForeground(new java.awt.Color(227, 227, 227));
        jBtnBundle4.setText("Book Now");
        jBtnBundle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBundle4ActionPerformed(evt);
            }
        });
        add(jBtnBundle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 140, -1));

        jBtnBundle1.setBackground(new java.awt.Color(165, 106, 219));
        jBtnBundle1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnBundle1.setForeground(new java.awt.Color(227, 227, 227));
        jBtnBundle1.setText("Book Now");
        jBtnBundle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBundle1ActionPerformed(evt);
            }
        });
        add(jBtnBundle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 140, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(231, 219, 239));
        jLabel17.setText("- 2 Mix Platter");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 170, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(231, 219, 239));
        jLabel13.setText("- 2 Glass Mango Juice");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 170, 20));

        jBtnBundle3.setBackground(new java.awt.Color(165, 106, 219));
        jBtnBundle3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnBundle3.setForeground(new java.awt.Color(227, 227, 227));
        jBtnBundle3.setText("Book Now");
        jBtnBundle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBundle3ActionPerformed(evt);
            }
        });
        add(jBtnBundle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 140, -1));

        jLabel2.setBackground(new java.awt.Color(153, 0, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/VIP.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 150, 150));

        jLabel8.setBackground(new java.awt.Color(153, 0, 153));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Large.png"))); // NOI18N
        jLabel8.setText("jLabel1");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 150, 150));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(231, 219, 239));
        jLabel16.setText("- Free Room 2 Hour(Medium)");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 190, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(231, 219, 239));
        jLabel21.setText("Pilih Bundle Yang Anda Suka");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bannerKategori.jpg"))); // NOI18N
        jLabel24.setText("jLabel24");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 750, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBundle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBundle2ActionPerformed
        // TODO add your handling code here:
        main.setFormPesanBundleView();
    }//GEN-LAST:event_jBtnBundle2ActionPerformed

    private void jBtnBundle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBundle1ActionPerformed
        // TODO add your handling code here:
        main.setFormPesanBundleView();
    }//GEN-LAST:event_jBtnBundle1ActionPerformed

    private void jBtnBundle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBundle3ActionPerformed
        // TODO add your handling code here:
        main.setFormPesanBundleView();
    }//GEN-LAST:event_jBtnBundle3ActionPerformed

    private void jBtnBundle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBundle4ActionPerformed
        // TODO add your handling code here:
        main.setFormPesanBundleView();
    }//GEN-LAST:event_jBtnBundle4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBundle1;
    private javax.swing.JButton jBtnBundle2;
    private javax.swing.JButton jBtnBundle3;
    private javax.swing.JButton jBtnBundle4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
