/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author fahaw
 */
public class CustomView extends javax.swing.JPanel {

    /**
     * Creates new form CustomView
     */
    private Main main;
    
    public CustomView(Main main) {
        initComponents();
        setOpaque(false);
        this.main = main;
        
    }
    
    @Override
    protected void paintComponent(Graphics grphcs){
        Graphics2D g2=(Graphics2D)grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#140919"), 0, getHeight(), Color.decode("#190924"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnCustom2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jBtnCustom4 = new javax.swing.JButton();
        jBtnCustom1 = new javax.swing.JButton();
        jBtnCustom3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(5, 3, 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(231, 219, 239));
        jLabel22.setText("Capacity 10 Person");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 170, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 219, 239));
        jLabel5.setText("VIP ROOM");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 150, 50));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(231, 219, 239));
        jLabel20.setText("Capacity 8 Person");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 170, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(231, 219, 239));
        jLabel10.setText("Capacity 4 Person");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 219, 239));
        jLabel1.setText("SMALL ROOM");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 150, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(231, 219, 239));
        jLabel15.setText("Rp. 50.000/Jam");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 170, 20));

        jLabel9.setBackground(new java.awt.Color(153, 0, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/small.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 150, 150));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(231, 219, 239));
        jLabel19.setText("Rp. 80.000/Jam");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 170, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 219, 239));
        jLabel3.setText("LARGE ROOM");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 150, 50));

        jBtnCustom2.setBackground(new java.awt.Color(165, 106, 219));
        jBtnCustom2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnCustom2.setForeground(new java.awt.Color(227, 227, 227));
        jBtnCustom2.setText("Book Now");
        jBtnCustom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCustom2ActionPerformed(evt);
            }
        });
        add(jBtnCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 219, 239));
        jLabel4.setText("MEDIUM ROOM");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 150, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(231, 219, 239));
        jLabel11.setText("Rp. 35.000/Jam");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 170, 20));

        jLabel7.setBackground(new java.awt.Color(153, 0, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Medium.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 150, 150));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(231, 219, 239));
        jLabel23.setText("Rp. 125.000/Jam");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 170, 20));

        jBtnCustom4.setBackground(new java.awt.Color(165, 106, 219));
        jBtnCustom4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnCustom4.setForeground(new java.awt.Color(227, 227, 227));
        jBtnCustom4.setText("Book Now");
        jBtnCustom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCustom4ActionPerformed(evt);
            }
        });
        add(jBtnCustom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 140, -1));

        jBtnCustom1.setBackground(new java.awt.Color(165, 106, 219));
        jBtnCustom1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnCustom1.setForeground(new java.awt.Color(227, 227, 227));
        jBtnCustom1.setText("Book Now");
        jBtnCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCustom1ActionPerformed(evt);
            }
        });
        add(jBtnCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 140, -1));

        jBtnCustom3.setBackground(new java.awt.Color(165, 106, 219));
        jBtnCustom3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnCustom3.setForeground(new java.awt.Color(227, 227, 227));
        jBtnCustom3.setText("Book Now");
        jBtnCustom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCustom3ActionPerformed(evt);
            }
        });
        add(jBtnCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 140, -1));

        jLabel2.setBackground(new java.awt.Color(153, 0, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/VIP.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 150, 150));

        jLabel8.setBackground(new java.awt.Color(153, 0, 153));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Large.png"))); // NOI18N
        jLabel8.setText("jLabel1");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 150, 150));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(231, 219, 239));
        jLabel16.setText("Capacity 6 Person");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 190, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(231, 219, 239));
        jLabel21.setText("Pilih Pesanan Sesuai Kemauan");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bannerKategori.jpg"))); // NOI18N
        jLabel24.setText("jLabel24");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 750, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCustom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCustom2ActionPerformed
        // TODO add your handling code here:
        main.setFormPesanCustomView();
    }//GEN-LAST:event_jBtnCustom2ActionPerformed

    private void jBtnCustom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCustom4ActionPerformed
        // TODO add your handling code here:
        main.setFormPesanCustomView();
    }//GEN-LAST:event_jBtnCustom4ActionPerformed

    private void jBtnCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCustom1ActionPerformed
        // TODO add your handling code here:
        main.setFormPesanCustomView();
    }//GEN-LAST:event_jBtnCustom1ActionPerformed

    private void jBtnCustom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCustom3ActionPerformed
        // TODO add your handling code here:
        main.setFormPesanCustomView();
    }//GEN-LAST:event_jBtnCustom3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCustom1;
    private javax.swing.JButton jBtnCustom2;
    private javax.swing.JButton jBtnCustom3;
    private javax.swing.JButton jBtnCustom4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
