/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import controller.BookingController;
import model.Booking;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author fahaw
 */
public class DaftarDataBooking extends javax.swing.JPanel {
private BookingController controller;
    private DefaultTableModel model;

    public DaftarDataBooking() {
        initComponents();
        controller = new BookingController();
        initTableModel();
        loadTableData();

        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                loadTableData();
            }
        });
    }
    
    
     private void initTableModel() {
        model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Kode");
        model.addColumn("Nama");
        model.addColumn("Telp");
        model.addColumn("Tgl");
        model.addColumn("Jam");
        model.addColumn("Durasi (Jam)");
        model.addColumn("Jenis");
        model.addColumn("Detail");
        model.addColumn("F&D");
        model.addColumn("Total (Rp)");
        
        jTable1.setModel(model);
    }

    
    public void loadTableData() {
        model.setRowCount(0);

        List<Booking> bookings = controller.getAllBookings();
        if (bookings != null) {
            for (Booking b : bookings) {
                model.addRow(new Object[]{
                    b.getId(), 
                    b.getKode(), 
                    b.getNama(), 
                    b.getTlp(),
                    b.getTgl(), 
                    b.getJam(), 
                    b.getDurasi(), 
                    b.getJenis(),
                    b.getDetail(), 
                    b.getFnd(), 
                    b.getTotal()
                });
            }
        }
    }
    
    @Override
    protected void paintComponent(Graphics grphcs){
        Graphics2D g2=(Graphics2D)grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#140919"), 0, getHeight(), Color.decode("#190924"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        setBackground(new java.awt.Color(5, 2, 5));

        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(231, 219, 239));
        jLabel21.setText("DAFTAR PESANAN");

        jTable1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Kode", "Nama", "Telp", "Tgl", "Jam", "Durasi", "Jenis", "Detail", "FND", "Total"
            }
        ));
        jTable1.setRowHeight(60);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(306, 306, 306))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel21)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel21;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
