/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author fahaw
 */
public class FormEditData extends javax.swing.JPanel {

    /**
     * Creates new form FormEditData
     */
    public FormEditData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnCari = new javax.swing.JButton();
        jTxtMasukanKode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(5, 2, 5));
        setPreferredSize(new java.awt.Dimension(830, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnCari.setFont(new java.awt.Font("Segoe UI Semibold", 0, 19)); // NOI18N
        jBtnCari.setText("Cari");
        jBtnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCari(evt);
            }
        });
        jBtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCariActionPerformed(evt);
            }
        });
        add(jBtnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 55, -1, -1));

        jTxtMasukanKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMasukanKodeActionPerformed(evt);
            }
        });
        add(jTxtMasukanKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 264, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 219, 239));
        jLabel2.setText("Masukan Kode Booking : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 55, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCari(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCari
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCari

    private void jBtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCariActionPerformed

    private void jTxtMasukanKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMasukanKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMasukanKodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCari;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTxtMasukanKode;
    // End of variables declaration//GEN-END:variables
}
