/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import controller.BookingController;
import model.Booking;
import javax.swing.JOptionPane;
/**
 *
 * @author fahaw
 */
public class FormPesanBundle extends javax.swing.JPanel {

    private final BookingController controller;

    public FormPesanBundle() {
        initComponents();
        controller = new BookingController();
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics grphcs){
        Graphics2D g2=(Graphics2D)grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#140919"), 0, getHeight(), Color.decode("#190924"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextNoTelp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextTanggal = new javax.swing.JTextField();
        jTextJam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCmbBundle = new javax.swing.JComboBox<>();
        jTextDurasi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jChBoxIceTea = new javax.swing.JCheckBox();
        jChBoxFishnChip = new javax.swing.JCheckBox();
        jChBoxMangoJuice = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(5, 3, 5));
        setMinimumSize(new java.awt.Dimension(830, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 219, 239));
        jLabel1.setText("Isi Data Diri Anda");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 219, 239));
        jLabel2.setText("Nama");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, 30));

        jTextNama.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add(jTextNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 360, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 219, 239));
        jLabel3.setText("Nomor Telepon");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 30));

        jTextNoTelp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add(jTextNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 360, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 219, 239));
        jLabel4.setText("Tanggal Kedatangan (dd/mm/yyyy)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 270, 30));

        jTextTanggal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add(jTextTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 360, 30));

        jTextJam.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add(jTextJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 190, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 219, 239));
        jLabel5.setText("Jam Kedatangan (HH:mm)");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 190, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 219, 239));
        jLabel6.setText("Pilih Bundle");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 190, 30));

        jCmbBundle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jCmbBundle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family 1", "Family 2", "Family 3", "Family 4" }));
        add(jCmbBundle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 190, 40));

        jTextDurasi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add(jTextDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 160, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(231, 219, 239));
        jLabel11.setText("Durasi");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 50, 30));

        jButton1.setBackground(new java.awt.Color(165, 106, 219));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(227, 227, 227));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 120, 40));

        jButton2.setBackground(new java.awt.Color(165, 106, 219));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(227, 227, 227));
        jButton2.setText("Pesan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 120, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(231, 219, 239));
        jLabel9.setText("Pilih Makanan/Minuman (optional)");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 260, 30));

        jChBoxIceTea.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jChBoxIceTea.setForeground(new java.awt.Color(231, 219, 239));
        jChBoxIceTea.setText("Ice Tea");
        jChBoxIceTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChBoxIceTeaActionPerformed(evt);
            }
        });
        add(jChBoxIceTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jChBoxFishnChip.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jChBoxFishnChip.setForeground(new java.awt.Color(231, 219, 239));
        jChBoxFishnChip.setText("Fish n Chip");
        jChBoxFishnChip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChBoxFishnChipActionPerformed(evt);
            }
        });
        add(jChBoxFishnChip, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, -1, -1));

        jChBoxMangoJuice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jChBoxMangoJuice.setForeground(new java.awt.Color(231, 219, 239));
        jChBoxMangoJuice.setText("Mango Juice");
        jChBoxMangoJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChBoxMangoJuiceActionPerformed(evt);
            }
        });
        add(jChBoxMangoJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/FormPesan.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setPreferredSize(new java.awt.Dimension(830, 770));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextNama.setText("");
        jTextNoTelp.setText("");
        jTextTanggal.setText("");
        jTextJam.setText("");
        jTextDurasi.setText("");
        jCmbBundle.setSelectedIndex(0);
        jChBoxIceTea.setSelected(false);
        jChBoxFishnChip.setSelected(false);
        jChBoxMangoJuice.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTextNama.getText().trim().isEmpty() || jTextNoTelp.getText().trim().isEmpty() ||
            jTextTanggal.getText().trim().isEmpty() || jTextJam.getText().trim().isEmpty() ||
            jTextDurasi.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field data diri harus diisi!", "Input Tidak Lengkap", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int durasi = Integer.parseInt(jTextDurasi.getText());
            if (durasi <= 0) {
                JOptionPane.showMessageDialog(this, "Durasi harus lebih dari 0!", "Input Tidak Valid", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Booking booking = new Booking();
            booking.setNama(jTextNama.getText());
            booking.setTlp(jTextNoTelp.getText());
            booking.setTgl(jTextTanggal.getText());
            booking.setJam(jTextJam.getText());
            booking.setDurasi(durasi);
            booking.setJenis("Bundle");
            
            String selectedBundle = (String) jCmbBundle.getSelectedItem();
            booking.setDetail(selectedBundle);

            int totalHarga = 0;
            String fnbBundle = "";

            switch (selectedBundle) {
                case "Family 1":
                    totalHarga = 120000;
                    fnbBundle = "Room Small (2 Jam), 1 Pitcher Ice Tea, 1 Calamary, 1 Fish n Chip";
                    break;
                case "Family 2":
                    totalHarga = 175000;
                    fnbBundle = "Room Medium (2 Jam), 1 Pitcher Ice Tea, 2 Glass Mango Juice, 1 Calamary, 1 Fish n Chip";
                    break;
                case "Family 3":
                    totalHarga = 250000;
                    fnbBundle = "Room Large (2 Jam), 2 Pitcher Ice Tea, 2 Mix Platter";
                    break;
                case "Family 4":
                    totalHarga = 350000;
                    fnbBundle = "Room VIP (2 Jam), 2 Pitcher Orange Juice, 2 Mix Platter";
                    break;
            }

            StringBuilder fnbTambahan = new StringBuilder();
            if (jChBoxIceTea.isSelected()) { fnbTambahan.append("Ice Tea, "); totalHarga += 10000; }
            if (jChBoxFishnChip.isSelected()) { fnbTambahan.append("Fish n Chip, "); totalHarga += 25000; }
            if (jChBoxMangoJuice.isSelected()) { fnbTambahan.append("Mango Juice, "); totalHarga += 15000; }
            
            if (fnbTambahan.length() > 0) {
                booking.setFnd(fnbBundle + " | Tambahan: " + fnbTambahan.substring(0, fnbTambahan.length() - 2));
            } else {
                booking.setFnd(fnbBundle);
            }
            booking.setTotal(totalHarga);

            String kodeBooking = controller.createBooking(booking);
            
            if (kodeBooking != null) {
                JOptionPane.showMessageDialog(this, "Booking bundle berhasil! Simpan kode booking Anda:\n" + kodeBooking, "Sukses", JOptionPane.INFORMATION_MESSAGE);
                jButton1ActionPerformed(null); // Panggil aksi reset
            } else {
                JOptionPane.showMessageDialog(this, "Gagal melakukan booking!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input durasi harus berupa angka!", "Input Tidak Valid", JOptionPane.WARNING_MESSAGE);
        }                 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jChBoxIceTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChBoxIceTeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChBoxIceTeaActionPerformed

    private void jChBoxFishnChipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChBoxFishnChipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChBoxFishnChipActionPerformed

    private void jChBoxMangoJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChBoxMangoJuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChBoxMangoJuiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jChBoxFishnChip;
    private javax.swing.JCheckBox jChBoxIceTea;
    private javax.swing.JCheckBox jChBoxMangoJuice;
    private javax.swing.JComboBox<String> jCmbBundle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextDurasi;
    private javax.swing.JTextField jTextJam;
    private javax.swing.JTextField jTextNama;
    private javax.swing.JTextField jTextNoTelp;
    private javax.swing.JTextField jTextTanggal;
    // End of variables declaration//GEN-END:variables
}
