
package gui;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;


public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private MenuView menuView;
    private BundleView bundleView;
    private CustomView customView;
    private FormPesanBundle formBundle;
    private FormPesanCustom formCustom;
    private DaftarDataBooking dataBooking;
    private FormEditData formEdit;
    
    
    //mengatur panel di sebelah kanan 
    public void setMenuView(){
        if(menuView == null){
            menuView = new MenuView(this);
        }  
        panelBorder1.removeAll();
        panelBorder1.setLayout(new java.awt.BorderLayout()); 
        panelBorder1.add(menuView, java.awt.BorderLayout.CENTER);
        panelBorder1.revalidate();
        panelBorder1.repaint();
    }
    
    public void setBundleView(){
        if(bundleView == null){
            bundleView = new BundleView(this);
        }  
        panelBorder1.removeAll();
        panelBorder1.setLayout(new java.awt.BorderLayout()); 
        panelBorder1.add(bundleView, java.awt.BorderLayout.CENTER);
        panelBorder1.revalidate();
        panelBorder1.repaint();
    }
    
    public void setCustomView(){
        if(customView == null){
            customView = new CustomView(this);
        }  
        panelBorder1.removeAll();
        panelBorder1.setLayout(new java.awt.BorderLayout()); 
        panelBorder1.add(customView, java.awt.BorderLayout.CENTER);
        panelBorder1.revalidate();
        panelBorder1.repaint();
    }
    
    public void setFormPesanBundleView(){
        if (formBundle == null) {
            formBundle = new FormPesanBundle();
        }
        panelBorder1.removeAll();
        panelBorder1.setLayout(new java.awt.BorderLayout());
        panelBorder1.add(formBundle, java.awt.BorderLayout.CENTER);
        panelBorder1.revalidate();
        panelBorder1.repaint();
    }
    
    public void setFormPesanCustomView(){
        if (formCustom == null) {
            formCustom = new FormPesanCustom();
        }
        panelBorder1.removeAll();
        panelBorder1.setLayout(new java.awt.BorderLayout());
        panelBorder1.add(formCustom, java.awt.BorderLayout.CENTER);
        panelBorder1.revalidate();
        panelBorder1.repaint();
    }
    
    public void setDaftarDataBookingView(){
        if (dataBooking == null) {
            dataBooking = new DaftarDataBooking();
        }
        panelBorder1.removeAll();
        panelBorder1.setLayout(new java.awt.BorderLayout());
        panelBorder1.add(dataBooking, java.awt.BorderLayout.CENTER);
        panelBorder1.revalidate();
        panelBorder1.repaint();
    }
    
    public void setFormEditDataView(){
        if (formEdit == null) {
            formEdit = new FormEditData();
        }
        panelBorder1.removeAll();
        panelBorder1.setLayout(new java.awt.BorderLayout());
        panelBorder1.add(formEdit, java.awt.BorderLayout.CENTER);
        panelBorder1.revalidate();
        panelBorder1.repaint();
    }
    
    public void loginSebagaiAdmin() {
        jBtnBundle.setVisible(false);
        jBtnCustom.setVisible(false);
        jBtnTampilData.setVisible(true);
        jBtnKelolaData.setVisible(true);
        jBtnLogout.setVisible(true);
        jBtnAdmin.setVisible(false);
    }

    public void logoutAdmin() {
        jBtnBundle.setVisible(true);
        jBtnCustom.setVisible(true);
        jBtnTampilData.setVisible(false);
        jBtnKelolaData.setVisible(false);
        jBtnLogout.setVisible(false);
        jBtnAdmin.setVisible(true);
    }
    
    public Main() {
        initComponents();
        //tranparankan frame bawaaan
        setBackground(new Color(0, 0, 0, 0));
        setMenuView();
        jBtnTampilData.setVisible(false);
        jBtnKelolaData.setVisible(false);
        jBtnLogout.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel1 = new components.MenuPanel();
        panelBorder3 = new components.PanelBorder();
        menuPanel2 = new components.MenuPanel();
        jBtnHome = new javax.swing.JButton();
        jBtnBundle = new javax.swing.JButton();
        jBtnCustom = new javax.swing.JButton();
        jBtnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnAdmin = new javax.swing.JButton();
        jBtnTampilData = new javax.swing.JButton();
        jBtnKelolaData = new javax.swing.JButton();
        jBtnLogout = new javax.swing.JButton();
        panelBorder1 = new components.PanelBorder();

        javax.swing.GroupLayout menuPanel1Layout = new javax.swing.GroupLayout(menuPanel1);
        menuPanel1.setLayout(menuPanel1Layout);
        menuPanel1Layout.setHorizontalGroup(
            menuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        menuPanel1Layout.setVerticalGroup(
            menuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder3.setPreferredSize(new java.awt.Dimension(1024, 768));
        panelBorder3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel2.setBackground(new java.awt.Color(20, 9, 25));
        menuPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnHome.setBackground(new java.awt.Color(35, 22, 46));
        jBtnHome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnHome.setForeground(new java.awt.Color(180, 180, 184));
        jBtnHome.setText("HOME");
        jBtnHome.setBorderPainted(false);
        jBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHomeActionPerformed(evt);
            }
        });
        menuPanel2.add(jBtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, 50));

        jBtnBundle.setBackground(new java.awt.Color(20, 9, 25));
        jBtnBundle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnBundle.setForeground(new java.awt.Color(180, 180, 184));
        jBtnBundle.setText("BUNDLE BOOKING");
        jBtnBundle.setBorderPainted(false);
        jBtnBundle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBundleActionPerformed(evt);
            }
        });
        menuPanel2.add(jBtnBundle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 50));

        jBtnCustom.setBackground(new java.awt.Color(20, 9, 25));
        jBtnCustom.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnCustom.setForeground(new java.awt.Color(180, 180, 184));
        jBtnCustom.setText("CUSTOM BOOKING");
        jBtnCustom.setBorderPainted(false);
        jBtnCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCustomActionPerformed(evt);
            }
        });
        menuPanel2.add(jBtnCustom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 190, 50));

        jBtnKeluar.setBackground(new java.awt.Color(20, 9, 25));
        jBtnKeluar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnKeluar.setForeground(new java.awt.Color(180, 180, 184));
        jBtnKeluar.setText("KELUAR");
        jBtnKeluar.setBorderPainted(false);
        jBtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKeluarActionPerformed(evt);
            }
        });
        menuPanel2.add(jBtnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        menuPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 170));

        jBtnAdmin.setBackground(new java.awt.Color(20, 9, 25));
        jBtnAdmin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnAdmin.setForeground(new java.awt.Color(180, 180, 184));
        jBtnAdmin.setText("MODE ADMIN");
        jBtnAdmin.setBorderPainted(false);
        jBtnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdminActionPerformed(evt);
            }
        });
        menuPanel2.add(jBtnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 190, 50));

        jBtnTampilData.setBackground(new java.awt.Color(20, 9, 25));
        jBtnTampilData.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnTampilData.setForeground(new java.awt.Color(180, 180, 184));
        jBtnTampilData.setText("TAMPIL DATA");
        jBtnTampilData.setBorderPainted(false);
        jBtnTampilData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTampilDataActionPerformed(evt);
            }
        });
        menuPanel2.add(jBtnTampilData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 50));

        jBtnKelolaData.setBackground(new java.awt.Color(20, 9, 25));
        jBtnKelolaData.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnKelolaData.setForeground(new java.awt.Color(180, 180, 184));
        jBtnKelolaData.setText("KELOLA DATA");
        jBtnKelolaData.setBorderPainted(false);
        jBtnKelolaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKelolaDataActionPerformed(evt);
            }
        });
        menuPanel2.add(jBtnKelolaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 190, 50));

        jBtnLogout.setBackground(new java.awt.Color(20, 9, 25));
        jBtnLogout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBtnLogout.setForeground(new java.awt.Color(180, 180, 184));
        jBtnLogout.setText("LOGOUT");
        jBtnLogout.setBorderPainted(false);
        jBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogoutActionPerformed(evt);
            }
        });
        menuPanel2.add(jBtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 190, 50));

        panelBorder3.add(menuPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 770));

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        panelBorder3.add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 830, 770));

        getContentPane().add(panelBorder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHomeActionPerformed
        // TODO add your handling code here:
        jBtnHome.setBackground(new Color(35,22,46));
        jBtnBundle.setBackground(new Color(20,9,25));
        jBtnCustom.setBackground(new Color(20,9,25));
        
        setMenuView();
    }//GEN-LAST:event_jBtnHomeActionPerformed

    private void jBtnBundleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBundleActionPerformed
        // TODO add your handling code here:
        jBtnHome.setBackground(new Color(20,9,25));
        jBtnBundle.setBackground(new Color(35,22,46));
        jBtnCustom.setBackground(new Color(20,9,25));
        
        setBundleView();
    }//GEN-LAST:event_jBtnBundleActionPerformed

    public void goToBundleView(){
        jBtnBundleActionPerformed(null);
    }
    
    private void jBtnCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCustomActionPerformed
        // TODO add your handling code here:
        jBtnHome.setBackground(new Color(20,9,25));
        jBtnBundle.setBackground(new Color(20,9,25));
        jBtnCustom.setBackground(new Color(35,22,46));
        
        setCustomView();
    }//GEN-LAST:event_jBtnCustomActionPerformed

    private void jBtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKeluarActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(
                null,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi Keluar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (jawab == JOptionPane.YES_OPTION) {
            System.exit(0); 
        } 
    }//GEN-LAST:event_jBtnKeluarActionPerformed

    private void jBtnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdminActionPerformed
        // TODO add your handling code here:
        LoginAdmin login = new LoginAdmin(this, true); 
        login.setVisible(true);
        
    }//GEN-LAST:event_jBtnAdminActionPerformed

    private void jBtnTampilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTampilDataActionPerformed
        // TODO add your handling code here:
        jBtnHome.setBackground(new Color(20,9,25));
        jBtnTampilData.setBackground(new Color(35,22,46));
        jBtnKelolaData.setBackground(new Color(20,9,25));
        
        setDaftarDataBookingView();
    }//GEN-LAST:event_jBtnTampilDataActionPerformed

    private void jBtnKelolaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKelolaDataActionPerformed
        // TODO add your handling code here:
        jBtnHome.setBackground(new Color(20,9,25));
        jBtnTampilData.setBackground(new Color(20,9,25));
        jBtnKelolaData.setBackground(new Color(35,22,46));
        
        setFormEditDataView();
    }//GEN-LAST:event_jBtnKelolaDataActionPerformed

    private void jBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogoutActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(
            null,
            "Yakin ingin logout?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (jawab == JOptionPane.YES_OPTION) {
            logoutAdmin(); 
            setMenuView(); 
        }
    }//GEN-LAST:event_jBtnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel( new FlatDarkLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdmin;
    private javax.swing.JButton jBtnBundle;
    private javax.swing.JButton jBtnCustom;
    private javax.swing.JButton jBtnHome;
    private javax.swing.JButton jBtnKelolaData;
    private javax.swing.JButton jBtnKeluar;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JButton jBtnTampilData;
    private javax.swing.JLabel jLabel1;
    private components.MenuPanel menuPanel1;
    private components.MenuPanel menuPanel2;
    private components.PanelBorder panelBorder1;
    private components.PanelBorder panelBorder3;
    // End of variables declaration//GEN-END:variables

    public JButton getjBtnBundle() {
        return jBtnBundle;
    }

    public void setjBtnBundle(JButton jBtnBundle) {
        this.jBtnBundle = jBtnBundle;
    }


}
