/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import gui.Main;

/**
 *
 * @author fahaw
 */
public class MenuView extends javax.swing.JPanel {

    /**
     * Creates new form MenuView
     */
    private Main main;
    
    public MenuView(Main main) {
        initComponents();
        setOpaque(false);
        this.main = main;
    }
    @Override
    protected void paintComponent(Graphics grphcs){
        Graphics2D g2=(Graphics2D)grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#050205"), 0, getHeight(), Color.decode("#0E0314"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnBookNow = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(830, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnBookNow.setBackground(new java.awt.Color(165, 106, 219));
        jBtnBookNow.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jBtnBookNow.setForeground(new java.awt.Color(227, 227, 227));
        jBtnBookNow.setText("Book Now");
        jBtnBookNow.setBorderPainted(false);
        jBtnBookNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBookNowActionPerformed(evt);
            }
        });
        add(jBtnBookNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 555, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MenuUtama.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 770));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBookNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBookNowActionPerformed
        // TODO add your handling code here:
        if (main != null) {
            main.goToBundleView(); 
        }

    }//GEN-LAST:event_jBtnBookNowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBookNow;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
